fixtures:
  repositories:
    backports: "git://github.com/ptomulik/puppet-backports.git"
    portsutil: "git://github.com/ptomulik/puppet-portsutil.git"
    vash:  "git://github.com/ptomulik/puppet-vash.git"
  symlinks:
    portsng: "#{source_dir}"
