AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/Vagrantfile'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/Lambda:
  EnforcedStyle: lambda

